services:
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../../configs/kafka:/bitnami/kafka/config
      - ../../app-data/kafka/volumes:/bitnami/kafka/data
    networks:
      - big-data-network

networks:
  big-data-network:
    external: true