x-healthcheck-default: &healthcheck-default
  interval: ${HEALTHCHECK_INTERVAL}
  timeout: ${HEALTHCHECK_INTERVAL}
  retries: ${HEALTHCHECK_RETRIES}

services:
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./${PROJECT_NAME}/.env
    healthcheck:
      <<: *healthcheck-default
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
    volumes:
      - ${CONFIGS_DIR}/${PROJECT_NAME}:/bitnami/kafka/config
      - ${APP_DATA_DIR}/${PROJECT_NAME}/volumes:/bitnami/kafka/data
    networks:
      - ${BIG_DATA_NETWORK}
