

services:
  kafkaproducer:
    build:
      context: ${BUILD_CONTEXT}
    container_name: kafkaproducer
    ports:
      - "8085:8085"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
      - ${APP_DATA_DIR}:/app/data
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "pgrep -f 'python /app/kafkaproducer.py' || exit 1" ]
networks:
  big-data-network:
    external: true