x-build-config: &x-build-config # common build configuration
  context: ${BUILD_CONTEXT}
  args:
    PINOT_VERSION: ${PINOT_VERSION}

x-common-env-files: &x-common-env-files
  env_file:
    - ${ENV_SERVICE_FILE}

services:
  pinot-controller:
    build:
      <<: *x-build-config
    <<: *x-common-env-files
    container_name: pinot-controller
    hostname: pinot-controller
    ports:
      - "9000:9000"
    environment:
      - PINOT_COMPONENT=controller
      - CONTROLLER_HOST=pinot-controller
      - CONTROLLER_PORT=9000
      - CONTROLLER_DATA_DIR=/var/pinot/controller/data
      - CONTROLLER_VIP_HOST=pinot-controller
      - CONTROLLER_VIP_PORT=9000
      - ZK_ADDRESS=${ZK_ADDRESS}
      - PINOT_CLUSTER_NAME=${PINOT_CLUSTER_NAME}
    volumes:
      - ../../app-data/pinot/controller/data:/var/pinot/controller/data
      - ../../app-data/pinot/controller/logs:/var/pinot/controller/logs
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  pinot-broker:
    build:
      <<: *x-build-config
    <<: *x-common-env-files
    container_name: pinot-broker
    hostname: pinot-broker
    ports:
      - "8099:8099"
    environment:
      - PINOT_COMPONENT=broker
      - BROKER_HOST=pinot-broker
      - BROKER_PORT=8099
      - BROKER_QUERY_PORT=8099
      - BROKER_INSTANCE_ID=Broker_pinot-broker_8099
      - ZK_ADDRESS=${ZK_ADDRESS}
      - PINOT_CLUSTER_NAME=${PINOT_CLUSTER_NAME}
    volumes:
      - ../../app-data/pinot/broker/logs:/var/pinot/broker/logs
    depends_on:
      pinot-controller:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  pinot-server-1:
    build:
      <<: *x-build-config
    <<: *x-common-env-files
    container_name: pinot-server-1
    hostname: pinot-server-1
    ports:
      - "8098:8098"
      - "8097:8097"  # Admin port
    environment:
      - PINOT_COMPONENT=server
      - SERVER_HOST=pinot-server-1
      - SERVER_PORT=8098
      - SERVER_ADMIN_PORT=8097
      - SERVER_DATA_DIR=/var/pinot/server/data
      - SERVER_SEGMENT_DIR=/var/pinot/server/data/segments
      - SERVER_INSTANCE_ID=Server_pinot-server-1_8098
      - ZK_ADDRESS=${ZK_ADDRESS}
      - PINOT_CLUSTER_NAME=${PINOT_CLUSTER_NAME}
    volumes:
      - ../../app-data/pinot/server1/data:/var/pinot/server/data
      - ../../app-data/pinot/server1/logs:/var/pinot/server/logs
    depends_on:
      pinot-broker:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  pinot-server-2:
    build:
      <<: *x-build-config
    <<: *x-common-env-files
    container_name: pinot-server-2
    hostname: pinot-server-2
    ports:
      - "8198:8198"
      - "8197:8097"  # Admin port
    environment:
      - PINOT_COMPONENT=server
      - SERVER_HOST=pinot-server-2
      - SERVER_PORT=8198
      - SERVER_ADMIN_PORT=8197
      - SERVER_DATA_DIR=/var/pinot/server/data
      - SERVER_SEGMENT_DIR=/var/pinot/server/data/segments
      - SERVER_INSTANCE_ID=Server_pinot-server-2_8198
      - ZK_ADDRESS=${ZK_ADDRESS}
      - PINOT_CLUSTER_NAME=${PINOT_CLUSTER_NAME}
    volumes:
      - ../../app-data/pinot/server2/data:/var/pinot/server/data
      - ../../app-data/pinot/server2/logs:/var/pinot/server/logs
    depends_on:
      pinot-broker:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  pinot-minion:
    build:
      <<: *x-build-config
    <<: *x-common-env-files
    container_name: pinot-minion
    hostname: pinot-minion
    ports:
      - "9514:9514"
    environment:
      - PINOT_COMPONENT=minion
      - MINION_HOST=pinot-minion
      - MINION_PORT=9514
      - MINION_DATA_DIR=/var/pinot/minion/data
      - MINION_INSTANCE_ID=Minion_pinot-minion_9514
      - ZK_ADDRESS=${ZK_ADDRESS}
      - PINOT_CLUSTER_NAME=${PINOT_CLUSTER_NAME}
    volumes:
      - ../../app-data/pinot/minion/data:/var/pinot/minion/data
      - ../../app-data/pinot/minion/logs:/var/pinot/minion/logs
    depends_on:
      pinot-server-1:
        condition: service_healthy
      pinot-server-2:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9514/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  big-data-network:
    external: true