

services:
  pinot-controller:
    build:
      context: ${BUILD_CONTEXT}
      args:
        PINOT_VERSION: 1.2.0
    container_name: pinot-controller
    hostname: pinot-controller
    ports:
      - "9000:9000"
    environment:
      - PINOT_COMPONENT=controller
      - ZK_ADDRESS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - PINOT_CLUSTER_NAME=PinotCluster
      - CONTROLLER_HOST=pinot-controller
      - CONTROLLER_PORT=9000
      - CONTROLLER_DATA_DIR=/var/pinot/controller/data
      - CONTROLLER_VIP_HOST=pinot-controller
      - CONTROLLER_VIP_PORT=9000
    volumes:
      - ${APP_DATA_DIR}/controller/data:/var/pinot/controller/data
      - ${APP_DATA_DIR}/controller/logs:/var/pinot/controller/logs
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health" ]

  pinot-broker:
    build:
      context: ${BUILD_CONTEXT}
      args:
        PINOT_VERSION: 1.2.0
    container_name: pinot-broker
    hostname: pinot-broker
    ports:
      - "8099:8099"
    environment:
      - PINOT_COMPONENT=broker
      - ZK_ADDRESS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - PINOT_CLUSTER_NAME=PinotCluster
      - BROKER_HOST=pinot-broker
      - BROKER_PORT=8099
      - BROKER_QUERY_PORT=8099
      - BROKER_INSTANCE_ID=Broker_pinot-broker_8099
    volumes:
      - ${APP_DATA_DIR}/broker/logs:/var/pinot/broker/logs
    depends_on:
      pinot-controller:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:8099/health" ]

  pinot-server-1:
    build:
      context: ${BUILD_CONTEXT}
      args:
        PINOT_VERSION: 1.2.0
    container_name: pinot-server-1
    hostname: pinot-server-1
    ports:
      - "8098:8098"
      - "8097:8097"  # Admin port
    environment:
      - PINOT_COMPONENT=server
      - ZK_ADDRESS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - PINOT_CLUSTER_NAME=PinotCluster
      - SERVER_HOST=pinot-server-1
      - SERVER_PORT=8098
      - SERVER_ADMIN_PORT=8097
      - SERVER_DATA_DIR=/var/pinot/server/data
      - SERVER_SEGMENT_DIR=/var/pinot/server/data/segments
      - SERVER_INSTANCE_ID=Server_pinot-server-1_8098
    volumes:
      - ${APP_DATA_DIR}/server1/data:/var/pinot/server/data
      - ${APP_DATA_DIR}/server1/logs:/var/pinot/server/logs
    depends_on:
      pinot-broker:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:8097/health" ]

  pinot-server-2:
    build:
      context: ${BUILD_CONTEXT}
      args:
        PINOT_VERSION: 1.2.0
    container_name: pinot-server-2
    hostname: pinot-server-2
    ports:
      - "8198:8198"
      - "8197:8097"  # Admin port
    environment:
      - PINOT_COMPONENT=server
      - ZK_ADDRESS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - PINOT_CLUSTER_NAME=PinotCluster
      - SERVER_HOST=pinot-server-2
      - SERVER_PORT=8198
      - SERVER_ADMIN_PORT=8197
      - SERVER_DATA_DIR=/var/pinot/server/data
      - SERVER_SEGMENT_DIR=/var/pinot/server/data/segments
      - SERVER_INSTANCE_ID=Server_pinot-server-2_8198
    volumes:
      - ${APP_DATA_DIR}/server2/data:/var/pinot/server/data
      - ${APP_DATA_DIR}/server2/logs:/var/pinot/server/logs
    depends_on:
      pinot-broker:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:8097/health" ]

  pinot-minion:
    build:
      context: ${BUILD_CONTEXT}
      args:
        PINOT_VERSION: 1.2.0
    container_name: pinot-minion
    hostname: pinot-minion
    ports:
      - "9514:9514"
    environment:
      - PINOT_COMPONENT=minion
      - ZK_ADDRESS=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - PINOT_CLUSTER_NAME=PinotCluster
      - MINION_HOST=pinot-minion
      - MINION_PORT=9514
      - MINION_DATA_DIR=/var/pinot/minion/data
      - MINION_INSTANCE_ID=Minion_pinot-minion_9514
    volumes:
      - ${APP_DATA_DIR}/minion/data:/var/pinot/minion/data
      - ${APP_DATA_DIR}/minion/logs:/var/pinot/minion/logs
    depends_on:
      pinot-server-1:
        condition: service_healthy
      pinot-server-2:
        condition: service_healthy
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:9514/health" ]
networks:
  big-data-network:
    external: true