x-build-default: &build-default
  build:
    context: ${BUILD_CONTEXT}
    args:
      - JAVA_HOME=${JAVA_HOME}
      - JAVA_VERSION=${JAVA_VERSION}
      - FLINK_VERSION=${FLINK_VERSION}
      - FLINK_HOME=${FLINK_HOME}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_CONF_DIR}
      - HADOOP_VERSION=${HADOOP_VERSION}
      - SCALA_VERSION=${SCALA_VERSION}
      - FLINK_LIB_PATH=${FLINK_LIB_PATH}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}

x-healthcheck-default: &healthcheck-default
  interval: ${HEALTHCHECK_INTERVAL}
  timeout: ${HEALTHCHECK_TIMEOUT}
  retries: ${HEALTHCHECK_RETRIES}

services:
  jobmanager:
    <<: *build-default
    container_name: flink-jobmanager
    ports:
      - "${FLINK_JOBMANAGER_PORT}:${FLINK_JOBMANAGER_PORT}"
    healthcheck:
      <<: *healthcheck-default
      test: ["CMD-SHELL", "curl -f ${FLINK_JOBMANAGER_HEALTHCHECK_URL} || exit 1"]
    volumes:
      - flink_jobmanager_data:${FLINK_HOME}/data
      - flink_jobmanager_log:${FLINK_HOME}/log
      - ${CONFIGS_DIR}/flink-conf.yaml:${FLINK_HOME}/conf/flink-conf.yaml
      - ../configs/hadoop:${HADOOP_CONF_DIR}
      - ${APP_DATA_DIR}/data:${FLINK_HOME}/datasets
      - ${APP_DATA_DIR}/jars:${FLINK_HOME}/user-jars
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_CONF_DIR}
      - JAVA_HOME=${JAVA_HOME}
    command: ${FLINK_HOME}/bin/jobmanager.sh start-foreground
    networks:
      - ${BIG_DATA_NETWORK}

  taskmanager:
    <<: *build-default
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    healthcheck:
      <<: *healthcheck-default
      test: ["CMD-SHELL", "curl -sf ${FLINK_TASKMANAGER_HEALTHCHECK_URL} | grep 'taskmanagers' || exit 1"]
    volumes:
      - flink_taskmanager_data:${FLINK_HOME}/data
      - flink_taskmanager_log:${FLINK_HOME}/log
      - ${CONFIGS_DIR}/flink-conf.yaml:${FLINK_HOME}/conf/flink-conf.yaml
      - ../configs/hadoop:${HADOOP_CONF_DIR}
      - ${APP_DATA_DIR}/data:${FLINK_HOME}/datasets
      - ${APP_DATA_DIR}/jars:${FLINK_HOME}/user-jars
    environment:
      - FLINK_PROPERTIES=taskmanager.rpc.address:taskmanager
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_CONF_DIR=${HADOOP_CONF_DIR}
      - JAVA_HOME=${JAVA_HOME}
    command: ${FLINK_HOME}/bin/taskmanager.sh start-foreground
    networks:
      - ${BIG_DATA_NETWORK}

volumes:
  flink_jobmanager_data:
    driver: local
  flink_taskmanager_data:
    driver: local
  flink_jobmanager_log:
    driver: local
  flink_taskmanager_log:
    driver: local
