x-flink-build: &flink-build
  build:
    context: .
services:
  jobmanager:
    <<: *flink-build
    container_name: flink-jobmanager
    ports:
      - "${FLINK_JOBMANAGER_PORT}:${FLINK_JOBMANAGER_PORT}"
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - HADOOP_HOME=${FLINK_HADOOP_HOME}
      - HADOOP_CONF_DIR=${FLINK_HADOOP_CONF_DIR}
    command: ${FLINK_HOME}/bin/jobmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${FLINK_JOBMANAGER_HEALTHCHECK_URL} || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_INTERVAL}
      retries: ${HEALTHCHECK_RETRIES}
    volumes:
      - flink_jobmanager_data:${FLINK_HOME}
      - ../../configs/flink/flink-conf.yaml:${FLINK_HOME}/conf/flink-conf.yaml
      - ../../configs/hadoop:${FLINK_HADOOP_CONF_DIR}
      - ../../app-data/flink/data:${FLINK_HOME}/data
      - ../../app-data/flink/jars:${FLINK_HOME}/jars
    networks:
      - ${FLINK_NETWORK}

  taskmanager:
    <<: *flink-build
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    environment:
      - FLINK_PROPERTIES=taskmanager.rpc.address:taskmanager
      - HADOOP_HOME=${FLINK_HADOOP_HOME}
      - HADOOP_CONF_DIR=${FLINK_HADOOP_CONF_DIR}
    command: ${FLINK_HOME}/bin/taskmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -sf ${FLINK_TASKMANAGER_HEALTHCHECK_URL} | grep 'taskmanagers' || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_INTERVAL}
      retries: ${HEALTHCHECK_RETRIES}
    volumes:
      - flink_taskmanager_data:${FLINK_HOME}
      - ../../configs/flink/flink-conf.yaml:${FLINK_HOME}/conf/flink-conf.yaml
      - ../../configs/hadoop:${FLINK_HADOOP_CONF_DIR}
      - ../../app-data/flink/data:${FLINK_HOME}/data
      - ../../app-data/flink/jars:${FLINK_HOME}/jars
    networks:
      - ${FLINK_NETWORK}

volumes:
  flink_jobmanager_data:
    driver: local
  flink_taskmanager_data:
    driver: local

networks:
  big-data-network:
    external: true