services:
  jobmanager:
    image: flink-local
    container_name: flink-jobmanager
    ports:
      - "8074:8074"
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager
      - HADOOP_HOME=/opt/hadoop-3.3.6
      - HADOOP_CONF_DIR=/opt/hadoop-3.3.6/etc/hadoop
    command: /opt/flink/bin/jobmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8074 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_jobmanager_data:/opt/flink
      - ../../configs/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ../../configs/hadoop:/opt/hadoop-3.3.6/etc/hadoop
      - ../../app-data/flink/data:/opt/flink/data
      - ../../app-data/flink/jars:/opt/flink/jars
    networks:
      - big-data-network

  taskmanager:
    image: flink-local
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    environment:
      - FLINK_PROPERTIES=taskmanager.rpc.address:taskmanager
      - HADOOP_HOME=/opt/hadoop-3.3.6
      - HADOOP_CONF_DIR=/opt/hadoop-3.3.6/etc/hadoop
    command: /opt/flink/bin/taskmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://jobmanager:8074/taskmanagers | grep 'taskmanagers' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_taskmanager_data:/opt/flink
      - ../../configs/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ../../configs/hadoop:/opt/hadoop-3.3.6/etc/hadoop
      - ../../app-data/flink/data:/opt/flink/data
      - ../../app-data/flink/jars:/opt/flink/jars
    networks:
      - big-data-network

volumes:
  flink_jobmanager_data:
    driver: local
  flink_taskmanager_data:
    driver: local

networks:
  big-data-network:
    external: true